name: da-main
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pandas
  - numpy
  - matplotlib
  - seaborn
  - scikit-learn
  - plotly
  - jupyter
  - ipykernel
  - notebook
  - nbformat
  - pip
  - pip:
      - black
      - nbstripout